### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by Phoenix1112** [lukeplausin/s3du#1]
hello. can you make a program that tries to identify the owner or website of an s3 hive? Imagine you found a bucket with clear permissions. how would you find the website that uses this bucket? If you can make such a program will be very valuable.

or i will make another suggestion. Do you know a way to find s3 buckets hidden behind cloudfront? this is a really hard job.. I am waiting for your reply. Are there some tactics you can offer me if you don't do this?

**Comment by lukeplausin** [comment]
Hi @Phoenix1112, the job you are asking about is not related to analysing storage space usage in S3, so I am going to close the proposal. Sorry about that.
